name: Run Scraper

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 12 * * *'
    - cron: '0 17 * * *'
    - cron: '0 22 * * *'
    - cron: '15 2 * * *'  # 23:15 hora de Argentina
  workflow_dispatch:  
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Cheerio
        run: npm install cheerio@^1.0.0-rc.12

      - name: Install Dotenv
        run: npm install dotenv@^17.2.2

      - name: Install Node-Fetch
        run: npm install node-fetch@^3.3.2

      - name: Install Nodemailer
        run: npm install nodemailer@^6.10.1

      - name: Install Playwright
        run:  npx playwright install                 
      
      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Install Puppeteer
        run: npm install puppeteer@^24.19.0

      - name: Install Playwright Chromium
        run: npx playwright install chromium

      - name: Run Scraper
        run: node index.js
        env:
          MY_MAIL: ${{ secrets.MY_MAIL }}
          MY_PASS: ${{ secrets.MY_PASS }}
